# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mt6895-beanpod/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mt6895-beanpod)

endif
